import { Employee } from '../types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: '1',
    firstName: 'Sarah',
    lastName: 'Connor',
    email: 'sarah.connor@cyberdyne.com',
    phone: '+1 (555) 123-4567',
    position: 'Lead Security Engineer',
    department: 'Engineering',
    hireDate: '2022-05-10',
    salary: 125000,
    status: 'Active',
  },
  {
    id: '2',
    firstName: 'Marcus',
    lastName: 'Wright',
    email: 'marcus.wright@cyberdyne.com',
    phone: '+1 (555) 987-6543',
    position: 'Operations Manager',
    department: 'Human Resources',
    hireDate: '2021-08-22',
    salary: 92000,
    status: 'Active',
  },
  {
    id: '3',
    firstName: 'Kyle',
    lastName: 'Reese',
    email: 'kyle.reese@cyberdyne.com',
    phone: '+1 (555) 444-2222',
    position: 'Field Specialist',
    department: 'Operations',
    hireDate: '2023-01-15',
    salary: 78000,
    status: 'On Leave',
  },
  {
    id: '4',
    firstName: 'John',
    lastName: 'Henry',
    email: 'john.henry@cyberdyne.com',
    phone: '+1 (555) 000-1111',
    position: 'AI Ethicist',
    department: 'Product',
    hireDate: '2020-11-03',
    salary: 145000,
    status: 'Active',
  },
  {
    id: '5',
    firstName: 'Cameron',
    lastName: 'Phillips',
    email: 'cameron.p@cyberdyne.com',
    phone: '+1 (555) 777-8888',
    position: 'Data Scientist',
    department: 'Engineering',
    hireDate: '2022-09-30',
    salary: 112000,
    status: 'Active',
  },
];